version: "3.7"
services:
  zookeeper:
    container_name: zookeeper_container_evento
    image: debezium/zookeeper:1.1
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    container_name: kafka_container_evento
    image: debezium/kafka:1.1
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
  kafdrop:
    container_name: kafdrop_container_evento
    image: obsidiandynamics/kafdrop:3.24.0
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
    ports:
      - 9066:9000
    depends_on:
      - kafka

  evento_db:
    image: postgres:9.6
    container_name: evento_db
    environment:
      - POSTGRES_DB=evento
      - POSTGRES_USER=evento
      - POSTGRES_PASSWORD=evento
      - TZ=GMT
    volumes:
      - db-evento:/var/lib/postgres/data
    ports:
      - 5431:5432

volumes:
  db-evento:
    driver: local